config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'projects#index'

  get 'up' => 'rails/health#show', as: :rails_health_check
  get 'dashboard' => 'dashboards#index', as: :dashboard
  resources :teams
  resources :projects
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
    <h2><%= t('errors.messages.not_saved', count: object.errors.count, resource: object.class.model_name.human) %></h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<%= turbo_frame_tag :notification do %>
  <% if notice || alert %>
    <div class="relative h-full max-w-5xl mx-auto px-4">
      <section class="mt-16">
        <div data-controller="notification" class="transition transform duration-1000 fixed inset-0 flex items-end justify-center px-4 py-6 pointer-events-none sm:p-6 sm:pt-16 sm:items-start sm:justify-end z-50" data-transition-enter-from="opacity-0 translate-x-6" data-transition-enter-to="opacity-100 translate-x-0" data-transition-leave-from="opacity-100 translate-x-0" data-transition-leave-to="opacity-0 translate-x-6">
          <div class="max-w-sm w-full bg-white shadow-lg pointer-events-auto rounded-lg shadow-xs overflow-hidden p-4">
            <div class="flex items-start">
              <% if notice %>
                <svg class="h-6 w-6 text-green-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
              <% else %>
                <svg class="h-6 w-6 text-red-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                </svg>
              <% end %>
              <div class="ml-3 w-0 flex-1 pt-0.5">
                <p class="text-sm font-medium text-gray-900">
                  <%= t('attention') %>
                </p>
                <p class="mt-1 text-sm text-gray-500">
                <%= notice || alert %>
                </p>
              </div>

              <div class="ml-4 flex-shrink-0 flex">
                <button data-action="notification#hide" class="bg-white rounded-md inline-flex text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500">
                  <span class="sr-only">Close</span>
                  <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  <% end %>
<% end %>

app/views/shared/_logo.html.erb
<div class='flex flex-row py-2'>
  <div class='basis-1/4 flex items-center justify-center'>
    <svg width="60px" height="60px" viewBox="0 0 48 48" id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg"><defs><style>.cls-1{fill:none;stroke:#FFFFFF;stroke-linecap:round;stroke-linejoin:round;}</style></defs><path class="cls-1" d="M40.5,5.5H7.5a2,2,0,0,0-2,2v33a2,2,0,0,0,2,2h33a2,2,0,0,0,2-2V7.5A2,2,0,0,0,40.5,5.5Z" /><line class="cls-1" x1="13.84" y1="10.5" x2="34.16" y2="10.5" /><line class="cls-1" x1="24" y1="37.5" x2="24" y2="10.5" /></svg>
  </div>
  <div class='basis-1/4 flex items-center justify-center'>
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                    width="60px" height="52px" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve"><g><line fill="none" stroke="#FFFFFF" stroke-width="2" stroke-miterlimit="10" x1="14" y1="31" x2="50" y2="31" /></g><g><circle fill="none" stroke="#FFFFFF" stroke-width="2" stroke-miterlimit="10" cx="32" cy="32" r="30.999" /></g> </svg>
  </div>
  <div class='basis-1/4 flex items-center justify-center'>
    <svg width="60px" height="60px" viewBox="0 0 48 48" id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg"><defs><style>.cls-1{fill:none;stroke:#FFFFFF;stroke-linecap:round;stroke-linejoin:round;}</style></defs><path class="cls-1" d="M40.5,5.5H7.5a2,2,0,0,0-2,2v33a2,2,0,0,0,2,2h33a2,2,0,0,0,2-2V7.5A2,2,0,0,0,40.5,5.5Z" /><path class="cls-1" d="M15,37.5v-27h4.57A13.48,13.48,0,0,1,33,24h0A13.48,13.48,0,0,1,19.55,37.5Z" /></svg>
  </div>
  <div class='basis-1/4 flex items-center justify-center'>
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                    width="60px" height="52px" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve"><g><line fill="none" stroke="#FFFFFF" stroke-width="2" stroke-miterlimit="10" x1="14" y1="31" x2="50" y2="31" /></g><g><circle fill="none" stroke="#FFFFFF" stroke-width="2" stroke-miterlimit="10" cx="32" cy="32" r="30.999" /></g>
    </svg>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="pt-2">
  <div class="rounded-t-lg bg-purple-360 px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <%= link_to root_path, class: 'flex flex-shrink-0' do %>
        <%= render 'shared/logo' %>
      <% end %>
      <div class="flex flex-1 items-start sm:items-stretch sm:justify-start">
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <% { pluralise_model(Team, 2) => teams_path, pluralise_model(Project, 2) => projects_path }.each_pair do |name, link| %>
              <%= link_to name, link, class: "#{request.path == link ? 'text-orange-360' : 'text-white hover:text-orange-360'} rounded-md px-3 py-2 text-sm font-medium" %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button id="dropdownUserAvatarButton" data-dropdown-toggle="dropdownAvatar" class="flex text-sm bg-gray-100 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300" type="button">
          <span class="sr-only">Open user menu</span>
          <img class="w-8 h-8 rounded-full" src=<%= current_user&.image_url %> alt="user photo">
        </button>
        <!-- Dropdown menu -->
        <div id="dropdownAvatar" class="z-10 hidden bg-gray-600 divide-y divide-gray-800 rounded-lg shadow w-48">
          <div class="px-4 mr-2 py-3 text-sm text-gray-400 dark:text-white">
            <div><%= current_user&.full_name %></div>
            <div class="font-medium truncate"><%= current_user&.email %></div>
          </div>
          <ul class="py-2 text-sm text-gray-700" aria-labelledby="dropdownUserAvatarButton">
            <li>
              <%= locale_link('pt-BR', class: 'flex items-center justify-between px-4 py-2 text-sm text-white hover:bg-gray-600') do %>
                <span>Português</span>
                <%= image_tag 'https://cdn.icon-icons.com/icons2/1694/PNG/512/brbrazilflag_111698.png', size: '25x15'  %>
              <% end %>
            </li>
            <li>
              <%= locale_link('en', class: 'flex items-center justify-between px-4 py-2 text-sm text-white hover:bg-gray-600') do %>
                <span>English</span>
                <%= image_tag 'https://static.vecteezy.com/system/resources/previews/005/416/914/original/flag-of-united-kingdom-illustration-free-vector.jpg', size: '25x15'  %>
              <% end %>
            </li>
          </ul>
          <div class="py-2">
            <%= link_to I18n.t('edit_profile'), edit_user_registration_path, class: 'block px-4 py-2 text-sm text-white hover:bg-gray-600' %>
            <%= link_to I18n.t('sign_out'), destroy_user_session_path, data: { turbo_method: :delete }, class: 'block px-4 py-2 text-sm text-white hover:bg-gray-600' %>
          </div>
        </div>

      </div>
    </div>
  </div>
</nav>