config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'projects#index'

  get 'up' => 'rails/health#show', as: :rails_health_check
  get 'dashboard' => 'dashboards#index', as: :dashboard
  resources :teams
  resources :projects
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id           :bigint           not null, primary key
#  project_name :string           not null
#  description  :text
#  policy       :integer          default("public"), not null
#  progress     :integer          default(0), not null
#  priority     :integer          default("low"), not null
#  due_date     :date             not null
#  team_id      :bigint           not null
#  creator_id   :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Project < ApplicationRecord
  # @extends ..................................................................
  enum policy: { public: 0, protected: 1, private: 2 }, _prefix: true
  enum priority: { low: 0, medium: 1, high: 2 }, _prefix: true

  # @includes .................................................................
  # @security (i.e. attr_accessible) ..........................................
  # @relationships ............................................................
  belongs_to :team
  belongs_to :creator, class_name: :User, foreign_key: :creator_id
  has_many :project_users, inverse_of: :project, dependent: :destroy
  has_many :users, through: :project_users

  has_many :tasks, inverse_of: :project, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: :all_blank

  # @validations ..............................................................
  validates :project_name, :policy, :progress, :priority, :due_date, presence: true
  validates :project_name, uniqueness: { scope: :creator_id }
  validate :check_if_creator_is_in_team

  # @callbacks ................................................................
  before_validation :set_policy
  before_validation :set_progress
  after_validation :set_members, unless: :policy_private?

  # @scopes ...................................................................
  scope :like, ->(search) { where('project_name ILIKE ?', "%#{search}%") }

  # @additional_config ........................................................
  # @class_methods ............................................................
  # @public_instance_methods ..................................................
  # Helper method to retrieve the creator and the team users.
  #
  # @return [Array]
  #
  def members
    [creator, *users].uniq
  end

  # @protected_instance_methods ...............................................

  protected

  # The `creator` of a project should always be in the team that the project
  # belongs to.
  #
  # @return [Boolean]
  #
  def check_if_creator_is_in_team
    return if errors.any?
    return if team.members.include?(creator)

    errors.add(:creator, 'is not in the team')
    false
  end

  # Sets `policy` to public for the project in case it was not previously set.
  #
  # @return [void]
  #
  def set_policy
    self.policy ||= :public
  end

  # Sets `progress` only based on the `progress` of the `tasks`.
  #
  # @return [void]
  #
  def set_progress
    return self.progress = 100 if tasks.empty?

    self.progress = tasks.sum(:progress) / tasks.size
  end

  # Sets `members` to the team members.
  #
  # @return [void]
  #
  def set_members
    return if errors.any?

    team.members.each do |user|
      next if project_users.map(&:user_id)&.include?(user.id)

      project_users.push ProjectUser.new(project: self, user:)
    end
  end

  # @private_instance_methods .................................................
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_teams, only: %i[new create edit update]
  before_action :set_helpers

  def index
    @projects = Project.like(params[:search]).includes(%i[tasks users]).order(:created_at)
  end

  def show; end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        flash[:notice] = t('notification.created', model: t('activerecord.models.project.one'))
        format.html { redirect_to project_url(@project) }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        flash[:notice] = t('notification.updated', model: t('activerecord.models.project.one'))
      else
        flash[:alert] = t('notification.not_updated', model: t('activerecord.models.project.one'))
      end
      format.turbo_stream
    end
  end

  def destroy
    @project.destroy!

    if @project.destroyed?
      flash[:notice] = t('notification.destroyed', model: t('activerecord.models.project.one'))
    else
      flash[:alert] = t('notification.not_destroyed', model: t('activerecord.models.project.one'))
    end

    respond_to(&:turbo_stream)
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_teams
    @teams = current_user.teams.pluck(:team_name, :id)
  end

  def set_helpers
    @users = User.where.not(id: current_user.id).pluck(:first_name, :id)
    @priorities = Project.priorities.keys
  end

  def project_params
    params.require(:project).permit(
      :project_name, :description, :progress, :priority, :due_date, :team_id, :creator_id,
      tasks_attributes: %i[id task_name description order progress priority due_date assignee_id _destroy]
    )
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_autosave_task_fields.html.erb
<th>
  <div class="pl-1">

    <%= form.select :assignee_id, project.users.pluck(:first_name, :id), {},
                    class: 'border-0 focus:border-0 bg-gray-100 focus:ring-0 focus:outline-none text-sm font-medium text-gray-900',
                    data: { action: 'change->autosave#save' } %>
  </div>
</th>
<th>
  <div class="ps-3">
    <%= form.text_field :task_name,
                        class: 'border-0 focus:border-0 bg-gray-100 focus:ring-0 focus:outline-none text-sm font-medium text-gray-900',
                        data: { action: 'keyup->autosave#save' } %>
  </div>
</th>
<th>
  <div class="ps-3">
    <%= form.text_field :description,
                        class: 'border-0 focus:border-0 bg-gray-100 focus:ring-0 focus:outline-none text-sm font-medium text-gray-900',
                        data: { action: 'keyup->autosave#save' } %>
  </div>
</th>
<th>
  <div class="ps-3">
    <%= form.select :priority, @priorities.map { |p| [attribute_model(Task, :priority, option: p), p] }, {},
                    class: 'border-0 focus:border-0 bg-gray-100 focus:ring-0 focus:outline-none text-sm font-medium text-gray-900',
                    data: { action: 'change->autosave#save' } %>
  </div>
</th>
<th>
  <div class='ps-3' data-controller='range'>
    <%= form.text_field :progress, type: :range,
                                   min: 0, max: 100, step: 25,
                                   class: 'w-full h-2 bg-gray-100 rounded-lg appearance-none cursor-pointer',
                                   data: { action: 'change->autosave#save range#update', range_target: 'input' } %>
  </div>
</th>
<th>
  <div class="ps-3">
    <%= form.date_field :due_date,
                        class: 'border-0 focus:border-0 bg-gray-100 focus:ring-0 focus:outline-none text-sm font-medium text-gray-900',
                        data: { action: 'change->autosave#save' } %>
  </div>
</th>
<th class="my-1 min-h-2">
  <%= form.submit action_model(:destroy, form.object),
                  class: 'border-0 focus:border-0 bg-gray-100 focus:ring-0 focus:outline-none text-sm font-medium text-gray-900',
                  data: { action: 'nested-form#submit_auto_save' } %>
</th>

app/views/projects/_form.html.erb
<% data = { controller: 'multi-step-form nested-form form-validate', nested_form_wrapper_selector_value: '.nested-form-wrapper' } %>
<%= form_with(model: @project, class: 'contents', data:) do |form| %>

  <div class='mt-5 mb-9'>
    <div class="flex-start flex h-3.5 w-full overflow-hidden rounded-full border border-gray-900/10 bg-gray-900/5 p-1 font-sans text-xs font-medium">
      <div class="flex items-center justify-center w-1/2 h-full overflow-hidden text-white break-all bg-orange-360 rounded-full"
           data-multi-step-form-target='progress'>
      </div>
    </div>
  </div>

  <%= render 'shared/errors', object: @project %>

  <div data-multi-step-form-target='step' data-step='0'>
    <div class="flex flex-col my-6">
      <%= render TextFieldComponent.new(form:, field: :project_name, options: { autofocus: true }) %>
    </div>

    <div class="flex flex-col my-6">
      <%= render TextFieldComponent.new(form:, field: :description, options: { type: :textarea, data: { controller: 'textarea-autogrow' } }) %>
    </div>

    <%= form.hidden_field :creator_id, value: current_user.id %>

    <div class="flex flex-col my-6">
      <%= render TextFieldComponent.new(form:, field: :team_id, items: @teams, options: { type: :select }) %>
    </div>

    <div class="flex space-x-12">
      <%= render RadioButtonComponent.new(form:, field: :priority, items: @priorities) %>
    </div>

    <div class="py-6">
      <%= render TextFieldComponent.new(form:, field: :due_date, options: { type: :date }) %>
    </div>

    <div class="flex space-x-12 justify-between">
      <div class="flex w-[200px] flex-col my-6">
        <%= render ButtonComponent.new(link: projects_path, options: { label: I18n.t('navigation.back'), colour: :light }) %>
      </div>
      <div class="flex w-[200px] flex-col my-6">
        <%= render ButtonComponent.new(options: { label: I18n.t('navigation.next'), colour: :orange, data: { action: 'multi-step-form#next', to: '1' } }) %>
      </div>
    </div>
  </div>

  <div data-multi-step-form-target='step' data-step='1'>
    <template data-nested-form-target="template">
      <%= form.fields_for :tasks, Task.new, child_index: 'NEW_RECORD' do |task_fields| %>
        <%= render 'task_fields', form: task_fields %>
      <% end %>
    </template>

    <%= form.fields_for :tasks do |task_fields| %>
      <%= render 'task_fields', form: task_fields %>
    <% end %>

    <!-- inserted elements -->
    <div data-nested-form-target='target'></div>

    <%= render ButtonComponent.new(options: { label: action_model(:newa, Task), colour: :orange, data: { action: 'nested-form#add' } }) %>

    <div class="flex space-x-12 justify-between">
      <div class="flex w-[200px] flex-col my-6">
        <%= render ButtonComponent.new(options: { label: I18n.t('navigation.previous'), colour: :light, data: { action: 'multi-step-form#previous', to: '0' } }) %>
      </div>
      <div class="flex w-[200px] flex-col my-6">
        <%= render ButtonComponent.new(form:, options: { label: action_model(:create, Project), colour: :indigo }) %>
      </div>
    </div>
  </div>

<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>" class='py-12 my-8 px-1 bg-zinc-100 ring-1 ring-black rounded-lg'>
  <% data = { controller: 'nested-form autosave', nested_form_wrapper_selector_value: '#nested-form-wrapper' } %>
  <%= form_with(model: project, class: 'contents text-black', data:) do |form| %>
    <div class="flex space-x-12 justify-between">
      <%= form.text_field :project_name,
                          class: 'mb-4 border-0 bg-zinc-100 focus:border-0 focus:ring-0 focus:outline-none text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl',
                          data: { action: 'keyup->autosave#save' } %>
      <div class="w-1/10 pt-2">
        <%= render ButtonComponent.new(
              link: edit_project_path(project.id),
              options: { label: action_model(:edit, project), colour: :indigo }
            ) %>
        <hr>
        <%= render ButtonComponent.new(
              link: project_path(project.id),
              options: { label: action_model(:destroy, project), colour: :red,
                         data: { turbo_method: :delete, turbo_confirm: t('confirmation.sure'), modal_hide: 'popup-modal' } }
            ) %>
      </div>
    </div>

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <div class="absolute px-4 -translate-x-1/2 bg-white left-1/2">
        <svg class="w-4 h-4 text-gray-700 dark:text-gray-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 14">
          <path d="M6 0H2a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h4v1a3 3 0 0 1-3 3H2a1 1 0 0 0 0 2h1a5.006 5.006 0 0 0 5-5V2a2 2 0 0 0-2-2Zm10 0h-4a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h4v1a3 3 0 0 1-3 3h-1a1 1 0 0 0 0 2h1a5.006 5.006 0 0 0 5-5V2a2 2 0 0 0-2-2Z"/>
        </svg>
      </div>
      <%= form.text_area :description,
                         class: 'text-gray-500 px-4 w-full border-1 border-gray-300 rounded-lg focus:ring-transparent focus:outline-none',
                         data: { action: 'keyup->autosave#save' } %>

      <table class="w-full text-sm text-left rtl:text-right text-gray-700 bg-gray-100">
        <thead class="text-xs text-gray-700 uppercase border-b border-black bg-gray-50">
          <tr>
            <th scope="col" class="px-3 py-3"><%= attribute_model(Task, :assignee) %></th>
            <th scope="col" class="px-6 py-3"><%= attribute_model(Task, :task_name) %></th>
            <th scope="col" class="px-6 py-3"><%= attribute_model(Task, :description) %></th>
            <th scope="col" class="px-6 py-3"><%= attribute_model(Task, :priority) %></th>
            <th scope="col" class="px-6 py-3"><%= attribute_model(Task, :progress) %></th>
            <th scope="col" class="px-6 py-3"><%= attribute_model(Task, :due_date) %></th>
            <th scope="col" class="px-6 py-3"><%= t('actions_column') %></th>
          </tr>
        </thead>
        <tbody class=border-b>
          <template data-nested-form-target="template">
            <%= form.fields_for :tasks, Task.new, child_index: 'NEW_RECORD' do |task_form| %>
              <tr id="nested-form-wrapper" data-new-record="<%= form.object.new_record? %>">
                <%= render 'autosave_task_fields', form: task_form, project: %>
              </tr>
            <% end %>
          </template>

          <%= form.fields_for :tasks do |task_form| %>
            <tr id="nested-form-wrapper" data-new-record="<%= form.object.new_record? %>">
              <%= render 'autosave_task_fields', form: task_form, project: %>
            </tr>
          <% end %>

          <!-- inserted elements -->
          <tr>
            <td data-nested-form-target='target'></td>
          </tr>

        </tbody>
      </table>
      <div class="w-1/3 py-2 mx-auto">
        <%= render ButtonComponent.new(options: { label: action_model(:newa, Task), colour: :orange, data: { action: 'nested-form#add' } }) %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/_search.html.erb
<%= form_with(url: 'projects/', local: true, method: :get, class: 'relative') do |form| %>
  <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none"></div>
  <%= form.text_field :search, class: 'block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500', required: true, id: 'default-search' %>
  <%= form.submit 'Search', class: 'text-black absolute end-2.5 bottom-2.5 bg-gray-600 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2' %>
<% end %>

app/views/projects/_task_fields.html.erb
<div class="nested-form-wrapper" data-new-record="<%= form.object.new_record? %>">
  <div class="flex space-x-12">
    <div class="flex w-[200px] flex-col my-5">
      <%= render TextFieldComponent.new(form:, field: :assignee_id, items: @users, options: { type: :select }) %>
    </div>

      <div class="flex w-full flex-col my-5">
      <%= render TextFieldComponent.new(form:, field: :task_name, options: { autofocus: true }) %>
    </div>
  </div>

  <div class="flex flex-col py-5">
    <%= render TextFieldComponent.new(form:, field: :description, options: { type: :textarea, data: { controller: 'textarea-autogrow' } }) %>
  </div>

  <!-- TODO: DRY and move to ViewComponent -->
  <div class="flex flex-col py-5" data-controller='range'>
    <%= form.text_field :progress,
                        type: :range,
                        class: 'w-full h-2 rounded-lg appearance-none cursor-pointer',
                        min: 0, max: 100, step: 25, value: 25,
                        data: { action: 'range#update', range_target: 'input' } %>

    <div class="w-full flex justify-between text-xs p-2">
      <span class='text-gray-500 dark:text-gray-400'>Didn't start</span>
      <span class='text-gray-500 dark:text-gray-400'>Just started</span>
      <span class='text-gray-500 dark:text-gray-400'>Halfway there</span>
      <span class='text-gray-500 dark:text-gray-400'>Almost finished</span>
      <span class='text-gray-500 dark:text-gray-400'>Done!</span>
    </div>
  </div>

  <div class="flex space-x-12">
    <%= render RadioButtonComponent.new(form:, field: :priority, items: @priorities) %>
  </div>

  <%= render TextFieldComponent.new(form:, field: :due_date, options: { type: :date }) %>

  <%= render ButtonComponent.new(options: { label: action_model(:destroy, Task), colour: :red, data: { action: 'nested-form#remove' } }) %>
</div>

app/views/projects/destroy.turbo_stream.erb
 <%= turbo_stream.append :notification, partial: 'shared/flash' %>

 <% if @project.destroyed? %>
  <%= turbo_stream.remove @project %>
 <% end %>

app/views/projects/edit.html.erb
<div class="mx-auto w-full md:w-2/3">
  <div class="text-center">
    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/index.html.erb
<div class='w-full'>
  <div class='flex justify-between'>
    <%= link_to action_model(:new, @projects), new_project_path, class: 'rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium' %>
    <%= render 'search' %>
  </div>

  <div id='projects' class='min-w-full py-4'>
    <%= render @projects %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="mx-auto w-full md:w-2/3">
  <div class="text-center">
    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @project %>

    <%= link_to 'Edit this project', edit_project_path(@project), class: 'mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this project', project_path(@project), method: :delete, class: 'mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium' %>
    </div>
    <%= link_to 'Back to projects', projects_path, class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
  </div>
</div>

app/views/projects/update.turbo_stream.erb
 <%= turbo_stream.append :notification, partial: 'shared/flash' %>